INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (2,'Vegan Society');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (3,'Cruelty-Free');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (5,'European Vegetarian Society');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (5,'V-Label');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (6,'Vegetarian Society');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (7,'Certified Vegan');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (13,'Klimatkompenserad Zeromission Transporter');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (13,'Climate Compensated Zero Emission Transports');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (16,'A.I.S.E. Voluntary Sustainability Intiative');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (18,'B-Corp');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (18,'B-Corporation Certified');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (18,'Certified B');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (18,'B Corp');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (19,'1% for the planet');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (21,'Asthma and Allergy Association');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (21,'Astma och Allergi Förbundet');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (22,'Keyhole');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (22,'Green Keyhole');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (23,'Eesti Allergialiit tunnustab');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (25,'Nordic Swan Eco-Label');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (25,'Nordic Ecolabel');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (25,'Svanemärket ');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (26,'EU Ecolabel');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (26,'Bra Miljöval');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (27,'Good Environmental Choice');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (28,'Blue Angel');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (29,'Demeter');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (30,'BioAgriCert');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (31,'EcoCert');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (31,'EU Green Leaf');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (32,'EU Organic Logo');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (33,'ICEA Certificato Biologico');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (34,'KRAV');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (35,'Bio Suisse');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (36,'Debio');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (37,'Organic');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (38,'Soil Association Organic');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (40,'Svensk');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (40,'Från Sverige');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (40,'From Sweden ');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (41,'Bondeägda / Farmer Owned');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (42,'MSC');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (42,'Marine Stewardship Council');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (43,'Natrue');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (44,'Rainforest Alliance Certified');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (45,'UTZ Certified');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (45,'UTZ');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (49,'Recycled');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (50,'Recyclable');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (52,'FSC');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (52,'FSC 100%');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (52,'FSC Recycled');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (55,'Skinpack');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (56,'Carton');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (57,'Bottle');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (58,'Miscellaneous');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (59,'Flexible');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (60,'Flexible stand-up pouch');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (61,'Tub');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (62,'Aerosol');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (63,'Tray');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (64,'Jar');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (65,'Tube');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (66,'Plastic unspecified');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (67,'Board plastic lined');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (68,'Plastic HDPE');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (69,'Miscellaneous');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (70,'Multi layer board');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (71,'Plastic other');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (72,'Plastic PS');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (73,'Plastic PP');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (74,'Plastic PET');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (75,'Metal steel');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (76,'Metallised Film');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (77,'Multi laminate');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (78,'Solid white board');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (79,'Glass plain');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (80,'Metal aluminium');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (81,'Paper plastic lined');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (82,'Plastic LDPE');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (83,'Paper foil lined');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (84,'Plastic PE');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (85,'Board white lined');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (86,'Paper plain');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (87,'Ceramic');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (88,'Paper plain');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (89,'Plastic unspecified');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (90,'Plastic other');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (91,'Board white lined');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (92,'Wood');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (93,'Flexible');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (94,'Sleeve');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (95,'Carton');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (96,'Fair Trade');
INSERT INTO attribute_keyword(attribute_id, keyword) VALUES (97,'Hand In Hand');