INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (1,'Social','Animal Welfare','Leaping Bunny Animal Welfare Label','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (2,'Social','Animal Welfare','Vegan Society ','https://www.vegansociety.com/your-business/about-vegan-trademark','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (3,'Social','Animal Welfare','Cruelty-Free','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (4,'Social','Animal Welfare','Cruelty Free and Vegan (Rabbit Face)','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (5,'Social','Animal Welfare','European Vegetarian Union / V-Label','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (6,'Social','Animal Welfare','Vegetarian Society','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (7,'Social','Animal Welfare','Certified Vegan (Vegan.org)','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (8,'Social','Animal Welfare','Dolphin Safe/Dolphin Friendly','N/A','');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (9,'Social','Animal Welfare','Self-Declared Vegan','N/A','');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (10,'Environmental','CO2/Carbon','Storage chilled','N/A','Parse from Storage');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (11,'Environmental','CO2/Carbon','Storage frozen','N/A','Parse from Storage');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (12,'Environmental','CO2/Carbon','Storage shelf stable','N/A','Parse from Storage');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (13,'Environmental','CO2/Carbon','Climate Compensated Zero Emission Transports','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (14,'Environmental','CO2/Carbon','Imported Product','N/A','Parse from Import Status');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (15,'Environmental','Firm-Wide','Green Dot Finanical Contribution to Recycling','https://www.pro-e.org/the-green-dot-trademark','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (16,'Environmental','Firm-Wide','A.I.S.E. Voluntary Sustainability Intiative','https://www.sustainable-cleaning.com/en.home.orb','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (17,'Environmental','Firm-Wide','CO2 Compensated','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (18,'Environmental','Firm-Wide','B Corp','https://bcorporation.net/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (19,'Environmental','Firm-Wide','1% for the planet','https://www.onepercentfortheplanet.org/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (20,'Social','Firm-Wide','Good Shopping Guide Ethical Award','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (21,'Social','Health','Asthma and Allergy Association / Asthma Allergy Nordic Label','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (22,'Social','Health ','Green Keyhole','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (23,'Social','Health ','Eesti Allergialiit tunnustab','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (24,'Other','Ingredients','Ingredients','N/A','Specific ingredients need to be added as CIs');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (25,'Environmental','Life Cycle EcoLabel','Nordic Swan Eco-Label','https://www.nordic-ecolabel.org/product-groups/group/?productGroupCode=026','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (26,'Environmental','Life Cycle EcoLabel','EU Ecolabel','https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2017.180.01.0045.01.ENG&toc=OJ:L:2017:180:TOC','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (27,'Environmental','Life Cycle EcoLabel','Good Environmental Choice / Bra Miljöval','https://www.naturskyddsforeningen.se/bra-miljoval/kemiska-produkter','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (28,'Environmental','Life Cycle EcoLabel','Blue Angel','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (29,'Environmental','Organic','Demeter','https://www.demeter-usa.org/media/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (30,'Environmental','Organic','BioAgriCert','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (31,'Environmental','Organic','EcoCert','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (32,'Environmental','Organic','EU Organic Logo','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (33,'Environmental','Organic','ICEA Certificato Biologico','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (34,'Environmental','Organic','KRAV','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (35,'Environmental','Organic','Bio Suisse','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (36,'Environmental','Organic','Debio','https://debio.no/debios-merker/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (37,'Environmental','Organic','Self-Declared Organic','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (38,'Environmental','Organic','Soil Association Organic','https://www.soilassociation.org/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (39,'Environmental','Origin ','In European Union or EEA','N/A','Parse from Location of manufacture');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (40,'Environmental','Origin ','From Sweden','https://fransverige.se/konsument/vad-ar-fran-sverige/market-mjolk-fran-sverige/','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (41,'Social','Other','Bondeägda / Farmer Owned','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (42,'Environmental','Other','Marine Stewardship Council ','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (43,'Environmental','Other','Natrue','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (44,'Environmental','Other','Rainforest Alliance Certified','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (45,'Environmental','Other','UTZ Certified','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (46,'Environmental','Packaging/Recycling','Packaging Made of Recycled Materials','N/A','We may be able to understand if there is some part recycled. No exact numbers. Is that interesting?');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (47,'Environmental','Packaging/Recycling','Recyclable Mobius Loop (able to be recycled)','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (48,'Environmental','Packaging/Recycling','Made of 100% Recycled Materials ','N/A','We may be able to understand if there is some part recycled. No exact numbers. Is that interesting?');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (49,'Environmental','Packaging/Recycling','Recycled','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (50,'Environmental','Packaging/Recycling','Recyclable','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (51,'Environmental','Packaging/Recycling','Compostability Mark of European Bioplastics','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (52,'Environmental','Packaging/Recycling','Forest Stewardship Council (FSC)','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (53,'Environmental','Packaging/Recycling','PEFC','N/A','Not needed, replaced by Packaging info (see below)?');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (54,'Environmental','Packaging/Recycling','Terracycle','N/A','Only from image scan');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (55,'Environmental','Packaging/Recycling','Package Type: Skinpack','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (56,'Environmental','Packaging/Recycling','Package Type: Carton','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (57,'Environmental','Packaging/Recycling','Package Type: Bottle','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (58,'Environmental','Packaging/Recycling','Package Type: Miscellaneous','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (59,'Environmental','Packaging/Recycling','Package Type: Flexible','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (60,'Environmental','Packaging/Recycling','Package Type: Flexible stand-up pouch','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (61,'Environmental','Packaging/Recycling','Package Type: Tub','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (62,'Environmental','Packaging/Recycling','Package Type: Aerosol','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (63,'Environmental','Packaging/Recycling','Package Type: Tray','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (64,'Environmental','Packaging/Recycling','Package Type: Jar','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (65,'Environmental','Packaging/Recycling','Package Type: Tube','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (66,'Environmental','Packaging/Recycling','Package Material: Plastic unspecified','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (67,'Environmental','Packaging/Recycling','Package Material: Board plastic lined','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (68,'Environmental','Packaging/Recycling','Package Material: Plastic HDPE','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (69,'Environmental','Packaging/Recycling','Package Material: Miscellaneous','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (70,'Environmental','Packaging/Recycling','Package Material: Multi layer board','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (71,'Environmental','Packaging/Recycling','Package Material: Plastic other','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (72,'Environmental','Packaging/Recycling','Package Material: Plastic PS','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (73,'Environmental','Packaging/Recycling','Package Material: Plastic PP','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (74,'Environmental','Packaging/Recycling','Package Material: Plastic PET','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (75,'Environmental','Packaging/Recycling','Package Material: Metal steel','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (76,'Environmental','Packaging/Recycling','Package Material: Metallised Film','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (77,'Environmental','Packaging/Recycling','Package Material: Multi laminate','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (78,'Environmental','Packaging/Recycling','Package Material: Solid white board','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (79,'Environmental','Packaging/Recycling','Package Material: Glass plain','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (80,'Environmental','Packaging/Recycling','Package Material: Metal aluminium','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (81,'Environmental','Packaging/Recycling','Package Material: Paper plastic lined','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (82,'Environmental','Packaging/Recycling','Package Material: Plastic LDPE','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (83,'Environmental','Packaging/Recycling','Package Material: Paper foil lined','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (84,'Environmental','Packaging/Recycling','Package Material: Plastic PE','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (85,'Environmental','Packaging/Recycling','Package Material: Board white lined','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (86,'Environmental','Packaging/Recycling','Package Material: Paper plain','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (87,'Environmental','Packaging/Recycling','Package Material: Ceramic','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (88,'Environmental','Packaging/Recycling','Package Material Secondary: Paper plain','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (89,'Environmental','Packaging/Recycling','Package Material Secondary: Plastic unspecified','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (90,'Environmental','Packaging/Recycling','Package Material Secondary: Plastic other','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (91,'Environmental','Packaging/Recycling','Package Material Secondary: Board white lined','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (92,'Environmental','Packaging/Recycling','Package Material Secondary: Wood','N/A','Parse from Package Material');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (93,'Environmental','Packaging/Recycling','Package Type Secondary: Flexible','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (94,'Environmental','Packaging/Recycling','Package Type Secondary: Sleeve','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (95,'Environmental','Packaging/Recycling','Package Type Secondary: Carton','N/A','Parse from Package Type');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (96,'Social','Social Welfare','Fair Trade','N/A','Parse from Product Information');
INSERT INTO attribute(id,category,model_criteria,label,links,mintel) VALUES (97,'Social','Social Welfare','Hand In Hand','N/A','Parse from Product Information');